const S={
 fethi:['Fethipaşa visitor gallery','https://yandex.com.tr/maps/org/fethipasa_sosyal_tesisi/130860822746/'],
 ibb:['İBB social facilities','https://tesislerrezervasyon.ibb.istanbul/'],
 nakka:['Üsküdar municipality','https://www.uskudar.bel.tr/tr/main/pages/nakkastepe-millet-bahcesi/476'],
 nakmap:['Nakkaştepe visitor gallery','https://yandex.com.tr/maps/org/nakkastepe_millet_parki/64737672539/reviews/?page=2'],
 ota:['Otağtepe photo feature (2021)','https://www.ensonhaber.com/galeri/istanbulun-en-guzel-manzarali-yerleri'],
 sule:['GoTürkiye · Süleymaniye','https://goturkiye.com/istanbul/suleymaniye-mosque'],
 pierre:['GoTürkiye · Pierre Loti','https://goturkiye.com/istanbul/pierre-loti-hill'],
 murver:['Mürver · hours & reservations','https://www.murverrestaurant.com/'],
 novotel:['Novotel · Mürver terrace & gallery','https://www.novotelistanbulbosphorus.com/gourmet-bar-restaurant/murver-restaurant/'],
 mikla:['Mikla · reservations','https://www.miklarestaurant.com/reservation'],
 miklag:['Mikla · official gallery','https://www.miklarestaurant.com/gallery'],
 seven:['Seven Hills · official website','https://www.sevenhillsrestaurant.com/'],
 sevenhotel:['Seven Hills · restaurant access','https://www.sevenhillshotel.com/seven-hills-restaurant.html'],
 sevenmenu:['Seven Hills · menu','https://sevenhills.gooqr.com/en'],
 roof:['Swissôtel · 16 Roof','https://www.swissotelthebosphorus.com/dining/16-roof-restaurant/'],
 salacak:['Salacak visitor gallery','https://yandex.com.tr/maps/org/salacak_sahili/102936430143/'],
 ortakoy:['Ortaköy visitor gallery','https://yandex.com.tr/maps/org/ortakoy_meydani/92212469863/'],
 sapphire:['Sapphire · official tickets','https://sapphireskydeck.com/en/'],
 vista:['Sapphire · Vista café','https://sapphireskydeck.com/en/vista-cafe-restaurant/'],
 sapmap:['Sapphire visitor gallery','https://yandex.com/maps/org/sapphire_observation_deck/197010862519/panorama/'],
 camlica:['Çamlıca Tower · official tickets','https://camlicakule.istanbul/en'],
 galata:['Galata Tower · official visitor information','https://galatakulesi.gov.tr/ziyaret'],
 galatam:['Ministry · Galata Tower museum','https://muze.gov.tr/urun-detay?CatalogNo=WEB-GLT03-87-009'],
 ferry:['Şehir Hatları · Üsküdar–Karaköy–Eminönü','https://sehirhatlari.istanbul/en/timetables/domestic-trips/inner-istanbul-ferry-lines/uskudar-karakoy-eminonu-164'],
 short:['Şehir Hatları · Short Bosphorus Tour','https://sehirhatlari.istanbul/en/timetables/bosphorus-tours/short-bosphorus-tour-181'],
 long:['Şehir Hatları · Long Bosphorus Tour','https://sehirhatlari.istanbul/en/timetables/bosphorus-tours/long-bosphorus-tour-91'],
 fares:['Şehir Hatları · tour fares','https://sehirhatlari.istanbul/en/price-list/bosphorus-tours-78'],
 sunsetboat:['Şehir Hatları · Saturday sunset cruise','https://sehirhatlari.istanbul/en/timetables/bosphorus-tours/sunset-cruises-598'],
 metro:['Metro İstanbul · network & alerts','https://www.metro.istanbul/'],
 sun:['Sunrise & sunset · September 2026','https://www.timeanddate.com/sun/turkey/istanbul?month=9&year=2026'],
 airport:['Turkish Airlines · airport arrival guidance','https://www.turkishairlines.com/en-eg/any-questions/check-in/'],
 tea:['Harvard · tea & caffeine','https://nutritionsource.hsph.harvard.edu/food-features/tea/'],
 kofte:['Tarihi Sultanahmet Köftecisi Selim Usta','https://sultanahmetkoftesi.com/en/home-page/'],
 baklava:['Karaköy Güllüoğlu · menu & address','https://www.karakoygulluoglu.com/en/menu'],
 doner:['Metet Közde Döner · current address','https://metetdoner.com/'],
 beans:['Erzincanlı Ali Baba · official profile','https://www.instagram.com/kurufasulyecialibaba/']
};
// Real photographs. Context images are explicitly labelled, not presented as the exact view from a seat.
const P={
 f1:['https://avatars.mds.yandex.net/get-altay/19553098/2a0000019d064606a3c629486213548fa4b7/XXL_height','Fethipaşa: a waterside view through the trees','Visitor photo · Yandex Maps',S.fethi[1]],
 f2:['https://avatars.mds.yandex.net/get-altay/14907426/2a00000199cfa34fc481028a03b09fbaeaba/S','Fethipaşa: sunset and a ferry; small visitor preview','Ercan Koç · Yandex Maps (2025)',S.fethi[1]],
 n1:['https://avatars.mds.yandex.net/get-altay/18121248/2a0000019d9c94a308e8c351f830af889f3f/S','Nakkaştepe: bridge beyond the trees; small preview','Visitor photo · Yandex Maps',S.nakmap[1]],
 n2:['https://avatars.mds.yandex.net/get-altay/16416536/2a0000019d0a2bdf2fbc14b5fdd01664cb67/S','Nakkaştepe: telescope and Bosphorus Bridge; small preview','Visitor photo · Yandex Maps',S.nakmap[1]],
 o1:['https://icdn.ensonhaber.com/resimler/galeri/kok/2021/03/12/otaY.jpg','Otağtepe: garden steps above the Bosphorus','Ensonhaber · archive photo (2021)',S.ota[1]],
 o2:['https://lokalee-production.s3.amazonaws.com/recommendations/Otagtepe-Park-1668422949587.jpg','Otağtepe: the garden and northern Bosphorus','Lokalee · destination photo','https://lokalee.app/de/recommendations/otagtepe-park'],
 s1:['https://cdn2.goturkiye.com/istanbul-ci-1-suleymaniye-mosque-1400x788.jpg','Süleymaniye: courtyard setting, not the terrace panorama','GoTürkiye',S.sule[1]],
 s2:['https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5f/A_view_from_galata_bridge_-_panoramio.jpg/960px-A_view_from_galata_bridge_-_panoramio.jpg','Süleymaniye seen from Galata Bridge; context, not a view from the mosque','Haluk Comertel · 2008 · CC BY 3.0','https://commons.wikimedia.org/wiki/File:A_view_from_galata_bridge_-_panoramio.jpg'],
 p1:['https://upload.wikimedia.org/wikipedia/commons/6/6e/Goldenhorn.jpg','Pierre Loti: the Golden Horn panorama; archive image','Dale Harvey · 2007 · CC BY 2.0','https://commons.wikimedia.org/wiki/File:Goldenhorn.jpg'],
 p2:['https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Istanbul_-_Pierre_Loti_Cafe_-_01.jpg/960px-Istanbul_-_Pierre_Loti_Cafe_-_01.jpg','Pierre Loti: a second Golden Horn angle; archive image','Josep Llauradó · 2004/05 · CC BY-SA 2.1 ES','https://commons.wikimedia.org/wiki/File:Istanbul_-_Pierre_Loti_Cafe_-_01.jpg'],
 m1:['https://www.novotelistanbulbosphorus.com/wp-content/uploads/sites/41/2022/12/25.06.2022_M%C3%BCrver-13495-724x357.jpg','Mürver: a table facing the water and passing ships','Novotel / Mürver · official gallery',S.novotel[1]],
 m2:['https://www.novotelistanbulbosphorus.com/wp-content/uploads/sites/41/2022/12/25.06.2022_M%C3%BCrver-13599-724x357.jpg','Mürver: dining-room setting, not an outdoor table','Novotel / Mürver · official gallery',S.novotel[1]],
 k1:['https://www.miklarestaurant.com/media/nfcj4rs4/2.jpg','Mikla: Galata Tower, water and rooftops in golden light','Mikla · official gallery',S.miklag[1]],
 k2:['https://www.miklarestaurant.com/media/gyenlc5t/3.jpg','Mikla: open-air terrace after dark','Mikla · official gallery',S.miklag[1]],
 h1:['https://www.sevenhillsrestaurant.com/blog/must-visit-restaurant-in-istanbul-2.jpg','Seven Hills: terrace tables beside the monumental skyline','Seven Hills · official photograph','https://www.sevenhillsrestaurant.com/Blog-Pages/must-visit-restaurant-in-istanbul.html'],
 h2:['https://cf.bstatic.com/xdata/images/hotel/max1024x768/578536011.jpg?k=76c7716996d5c4f03225b889d55203235e4e884002e352d9c5665c211f45b10e&o=','Seven Hills: the photo-focused rooftop atmosphere','Seven Hills / Booking.com · property photo',S.seven[1]],
 r1:['https://dq5r178u4t83b.cloudfront.net/wp-content/uploads/sites/149/2023/04/07141616/16-Roof-Galeri-300x200.jpg','16 Roof: stepped terraces and the Bosphorus at dusk','Swissôtel · official gallery',S.roof[1]],
 r2:['https://dq5r178u4t83b.cloudfront.net/wp-content/uploads/sites/149/2025/11/25130313/A4F05741T-Copy-300x200.jpg','16 Roof: covered terrace seating','Swissôtel · official gallery',S.roof[1]],
 a1:['https://avatars.mds.yandex.net/get-altay/15696528/2a0000019fd6956637826162587676857797/XXL_height','Salacak: the Old City across the water on an overcast day','Visitor photo · Yandex Maps',S.salacak[1]],
 a2:['https://upload.wikimedia.org/wikipedia/commons/5/54/K%C4%B1z_Kulesi_%28131944865%29.jpeg','Maiden’s Tower after dark; atmospheric archive photo, colour treatment visible','Coşkun Kuruderviş (Commons credit) · 2012 · CC BY 3.0','https://commons.wikimedia.org/wiki/File:Kız_Kulesi_(131944865).jpeg'],
 t1:['https://avatars.mds.yandex.net/get-altay/19699569/2a0000019e55ef6105f34c5b1dee81703148/XXL_height','Ortaköy: mosque and bridge at blue hour; visitors in foreground','Visitor photo · Yandex Maps',S.ortakoy[1]],
 t2:['https://avatars.mds.yandex.net/get-altay/18100231/2a0000019e55ef8fb6aa2511f52dea51ac23/XXL_height','Ortaköy: kumpir stalls near the waterfront; neighbourhood context','Visitor photo · Yandex Maps',S.ortakoy[1]],
 b1:['https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b3/View_from_Galata_Bridge_looking_east_-_Istanbul%2834752858981%29.jpg/960px-View_from_Galata_Bridge_looking_east_-_Istanbul%2834752858981%29.jpg','Ferries seen from Galata Bridge; harbour context, not a promised vessel','Thomas Woodtli · 2017 · CC BY-SA 2.0','https://commons.wikimedia.org/wiki/File:View_from_Galata_Bridge_looking_east_-_Istanbul(34752858981).jpg'],
 v1:['https://avatars.mds.yandex.net/get-altay/13916077/2a000001958bb53fdb76e122c8316df55497/XXL_height','Sapphire: Levent skyscrapers and the distant Bosphorus','Visitor photo · Yandex Maps',S.sapmap[1]],
 v2:['https://sapphireskydeck.com/wp-content/uploads/2023/06/vista.jpg','Sapphire Vista: window-side dining above the city','Sapphire Skydeck · official café photo',S.vista[1]],
 c1:['https://camlicakule.istanbul/contents/piclib/content/173/features005-66639-3086184.jpg','Çamlıca Tower: the observation deck and city panorama','Çamlıca Tower · official gallery',S.camlica[1]],
 c2:['https://camlicakule.istanbul/contents/piclib/content/176/features002-66468-3773035.jpg','Çamlıca Tower: window-side restaurant setting','Çamlıca Tower · official gallery',S.camlica[1]],
 g1:['https://upload.wikimedia.org/wikipedia/commons/6/68/View_from_Galata_Tower%2C_Istanbul.jpg','Galata Tower: rooftops and the Golden Horn from the tower','Gah341 · 2018 · CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:View_from_Galata_Tower,_Istanbul.jpg']
};
const CATEGORIES=[['quiet','Gardens & quieter corners','The strongest candidates for a long, unhurried sit.'],['roof','Open-air rooftops','A seat with a view. A reservation is not a guarantee of silence.'],['water','Waterfronts & bridges','Big scenery without an observation-deck ticket.'],['tower','Above the skyline','Choose a clear day; a café and a viewing ticket are not interchangeable.'],['boat','Views from the water','Public crossings and official sightseeing cruises—not party boats.']];
const PLACES=[
{id:'fethi',cat:'quiet',name:'Fethipaşa Korusu',area:'Kuzguncuk · Üsküdar',view:'A leafy hillside above the Bosphorus: ferries, open water and the European shoreline. My first choice for thinking rather than ticking off sights.',best:'Weekdays 10:00–11:30. Late afternoon is prettier but busier.',time:['morning','afternoon','sunset'],peace:3,calm:'Choose an upper-path bench away from the café entrance. The café can be lively; the grove is not private.',cost:'Grove: usually free. Café: pay for your order.',budget:'free',access:'Park and café hours differ; check the café before making a special trip.',route:'Walk 4–7 min to Çemberlitaş → T1 to Eminönü → ferry to Üsküdar → 20–30 min walk, including a steep climb. A short taxi avoids the hill.',mins:'55–80 min',coffee:true,coords:[41.029,29.023],query:'Fethipaşa Korusu Üsküdar Istanbul',photos:['f1','f2'],sources:['ibb','fethi','ferry'],pick:'Best quiet sit'},
{id:'nakka',cat:'quiet',name:'Nakkaştepe Millet Bahçesi',area:'Kuzguncuk · Üsküdar',view:'The first Bosphorus bridge stretches across the trees below your viewpoint. More dramatic bridge scenery than most central cafés.',best:'Weekdays 09:00–11:00 or 16:00–17:00. Sunset draws more people.',time:['morning','afternoon','sunset'],peace:3,calm:'Walk away from the telescope/photo platforms and play areas. Popular with local families—not a secret park.',cost:'Public park; confirm current gate policy. Café purchases extra.',budget:'check',access:'Gate times and any access charge were not verified. Check before an early start.',route:'T1 to Eminönü → ferry to Üsküdar → short taxi uphill. Public-transport alternative: M5 to Altunizade, then a hilly walk.',mins:'65–95 min',coffee:true,coords:[41.0357,29.0379],query:'Nakkaştepe Millet Bahçesi Üsküdar',photos:['n1','n2'],sources:['nakka','nakmap','metro'],pick:'Best bridge panorama'},
{id:'ota',cat:'quiet',name:'Otağtepe · Fatih Korusu',area:'Kavacık / Beykoz · Asian side',view:'Terraced greenery high above the northern Bosphorus and the Fatih Sultan Mehmet Bridge. A genuinely sweeping view, but a long detour.',best:'Weekdays 10:00–12:00 or 15:00–16:30; not a sunset booking.',time:['morning','afternoon'],peace:3,calm:'A stronger relative-quiet candidate than famous central rooftops. Other visitors and photographers are still possible.',cost:'Usually described as free; current gate policy unconfirmed.',budget:'check',access:'Do not rely on sunset access: current closing time is unverified. Bring water; do not count on a café.',route:'T1 → Eminönü–Üsküdar ferry → taxi to Otağtepe. A northbound bus plus uphill last-mile walk is slower; use live Maps routing.',mins:'80–120 min',coffee:false,coords:[41.0859,29.068],query:'Otağtepe Fatih Korusu Istanbul',photos:['o1','o2'],sources:['ota'],pick:'Quiet detour, not core plan'},
{id:'sule',cat:'quiet',name:'Süleymaniye outer terrace',area:'Süleymaniye · Fatih',view:'Golden Horn, bridges and the city’s rooftops from the historic peninsula. An excellent near-hotel alternative to paying for another rooftop.',best:'Thursday 09:30–10:30 for atmosphere and relative calm; late afternoon for warmer light.',time:['morning','afternoon'],peace:3,calm:'A working mosque, not a lounge. Rest only where seating is permitted; keep food and conversation out of worship areas.',cost:'Free mosque / exterior visit.',budget:'free',access:'Daytime visitor access is subject to prayer and courtyard gates. Dress respectfully; avoid Friday prayer crowds.',route:'Walk roughly 20–30 min from the hotel via Beyazıt. Some slopes and uneven paving; descend towards Eminönü afterwards.',mins:'20–30 min',coffee:false,coords:[41.0163,28.9639],query:'Süleymaniye Camii Istanbul',photos:['s1','s2'],sources:['sule'],pick:'Best free near-hotel view'},
{id:'pierre',cat:'quiet',name:'Pierre Loti Hill & café',area:'Eyüpsultan · Golden Horn',view:'The Golden Horn curves away between layered neighbourhoods. A different, slower-feeling panorama from the Bosphorus.',best:'Weekday morning, around 09:00–10:00 after checking café / cable-car opening. Sunset is scenic but busier.',time:['morning','sunset'],peace:2,calm:'The lookout beside the cable car is a photo magnet. A café table away from the railing is the better long-sit option.',cost:'Viewpoint free; café, tram and cable car extra.',budget:'free',access:'Do not assume the café or cable car operates at sunrise. Historic photos illustrate the panorama, not today’s landscaping.',route:'T1 to Eminönü → T5 to Eyüpsultan Teleferik → TF2 cable car → short walk. The uphill walking route is an alternative.',mins:'60–85 min',coffee:true,coords:[41.0548,28.9335],query:'Pierre Loti Tepesi Istanbul',photos:['p1','p2'],sources:['pierre','metro'],pick:'Golden Horn alternative'},
{id:'murver',cat:'roof',name:'Mürver',area:'Novotel Bosphorus · Karaköy',view:'An elevated table facing passing ships and the historic peninsula. A strong combination of serious food and a water view.',best:'Early dinner 18:00–19:30; arrive before sunset rather than after it.',time:['sunset','night'],peace:2,calm:'Ask for an outdoor edge table away from speakers. The hotel advertises live DJ music: do not book it expecting silence.',cost:'Premium restaurant · menu-priced.',budget:'premium',access:'Dinner listed 18:00–22:00; bar from 17:00. Reserve the outdoor area specifically and confirm music / terrace availability.',route:'Çemberlitaş T1 → Karaköy → short waterfront walk to Novotel, Kemankeş Caddesi 57–59.',mins:'25–40 min',coffee:false,coords:[41.0238,28.979],query:'Mürver Restaurant Novotel Istanbul Bosphorus',photos:['m1','m2'],sources:['murver','novotel'],pick:'Arrival-night upgrade'},
{id:'mikla',cat:'roof',name:'Mikla rooftop',area:'The Marmara Pera · Beyoğlu',view:'Galata Tower, densely packed rooftops, the Golden Horn and the Bosphorus together. My strongest paid panorama for this short trip.',best:'Thursday 18:00 onwards: golden light → sunset 19:22 → illuminated skyline.',time:['sunset','night'],peace:2,calm:'Reserve a seated perimeter spot rather than assuming a quiet walk-in bar. Ask about music, events, minimum spend and table duration.',cost:'Premium bar / restaurant · confirm minimum spend.',budget:'premium',access:'Mon–Sat from 18:00; restaurant to midnight, bar later. Closed Sunday. Confirm whether a drinks-only outdoor seat is available.',route:'T1 to Karaköy → Tünel / uphill walk to Pera. Alternative: walk to Vezneciler → M2 Şişhane → walk. Meşrutiyet Caddesi 15.',mins:'35–50 min',coffee:false,coords:[41.031,28.9751],query:'Mikla Restaurant The Marmara Pera Istanbul',photos:['k1','k2'],sources:['mikla','miklag'],pick:'Reserve this view'},
{id:'seven',cat:'roof',name:'Seven Hills Restaurant',area:'Sultanahmet · a walk from your hotel',view:'Hagia Sophia and the Blue Mosque dominate the open rooftop. Spectacular for architecture photographs; less suited to privacy.',best:'Late afternoon and the hour around sunset. Dawn photos are better in the public squares, not at an unconfirmed rooftop opening.',time:['afternoon','sunset','night'],peace:1,calm:'Expect visitors coming to the edge for photographs. Choose this for the famous close-up view, not a meditative hour.',cost:'Restaurant / drinks priced for a tourist rooftop.',budget:'premium',access:'Hotel page lists 12:00–23:00, while breakfast is advertised elsewhere. Earlier access is unresolved: confirm directly. Tevkifhane Sokak 8.',route:'Walk approximately 15–20 min through Sultanahmet. No transit needed.',mins:'15–20 min',coffee:true,coords:[41.005,28.9802],query:'Seven Hills Restaurant Istanbul Sultanahmet',photos:['h1','h2'],sources:['seven','sevenhotel','sevenmenu'],pick:'Iconic, not peaceful'},
{id:'roof16',cat:'roof',name:'16 Roof · Swissôtel',area:'Maçka / Beşiktaş',view:'Broad Bosphorus scenery from an open terrace. Particularly impressive once bridge and shoreline lights come on.',best:'17:00–18:30 for the calmer window; after 19:00 for views with a nightlife atmosphere.',time:['afternoon','sunset','night'],peace:1,calm:'The venue explicitly schedules a DJ after 19:00. Not my recommendation for a quiet sunset.',cost:'Premium restaurant / bar.',budget:'premium',access:'Official hours 17:00–02:00; seasonal terrace, weather permitting. Reserve; check dress code and any minimum spend.',route:'T1 to Kabataş → taxi uphill to Swissôtel, Acısu Sokak 19. Walking the final hill is possible but tiring.',mins:'45–65 min',coffee:false,coords:[41.0415,28.9998],query:'16 Roof Swissotel The Bosphorus Istanbul',photos:['r1','r2'],sources:['roof'],pick:'Night-view alternative'},
{id:'salacak',cat:'water',name:'Salacak shoreline',area:'Opposite Maiden’s Tower · Üsküdar',view:'Maiden’s Tower close to the water, with the Old City silhouetted beyond it. The best fit for your Friday sunset.',best:'18:00–19:50 on Friday: sunset 19:20, then the first city lights.',time:['sunset','night'],peace:2,calm:'The classic tower photo point is busy. Walk along the shoreline until you find a less-trafficked seat; privacy is not guaranteed.',cost:'Public waterfront free; takeaway drink extra.',budget:'free',access:'Use current promenade access. Do not rely on old travel photos showing cushions or former tea stalls.',route:'T1 to Eminönü → ferry to Üsküdar → approximately 20–25 min walk south, or short taxi. Allow the same time back to the pier.',mins:'50–75 min',coffee:false,coords:[41.018,29.0118],query:'Salacak Sahili Üsküdar Istanbul',photos:['a1','a2'],sources:['salacak','sun','ferry'],pick:'Best sunset silhouette'},
{id:'ortakoy',cat:'water',name:'Ortaköy waterfront',area:'Mecidiye · Beşiktaş',view:'Ortaköy Mosque directly beside the Bosphorus, framed by the first bridge. An unmistakable postcard view.',best:'06:15–07:30 for early light and fewer people. After dusk for illuminated architecture, but not quiet.',time:['sunrise','morning','night'],peace:2,calm:'Dawn is the quieter bet. At night the square and food stalls can be very busy; this is not a hidden location.',cost:'Public square free; snacks / drinks extra.',budget:'free',access:'Dawn refers to the outdoor waterfront, not mosque interior or café access. Plan a taxi for an early start.',route:'At normal hours: T1 to Kabataş → shore bus / taxi. For sunrise use a taxi directly from the hotel; roads and traffic affect timing.',mins:'50–80 min by transit',coffee:false,coords:[41.0478,29.027],query:'Ortaköy Meydanı Istanbul',photos:['t1','t2'],sources:['ortakoy','sun'],pick:'Optional dawn swap'},
{id:'bridge',cat:'water',name:'Galata Bridge footways',area:'Eminönü ↔ Karaköy',view:'Ferries cutting across the water, domes on the hill and the Golden Horn opening out around you. A view to watch in motion.',best:'06:30–08:00 for a calmer crossing, or 19:30–20:15 for city lights.',time:['sunrise','morning','sunset','night'],peace:1,calm:'Traffic, anglers and pedestrians make this a short pause rather than a private sit. Use a nearby café for a longer break.',cost:'Free pedestrian crossing.',budget:'free',access:'Keep clear of fishing lines and narrow busy sections. Do not confuse this with the motorway bridges over the Bosphorus.',route:'T1 from Çemberlitaş to Eminönü → walk onto the bridge; continue to Karaköy if visiting Mürver or Güllüoğlu.',mins:'20–30 min',coffee:false,coords:[41.0196,28.973],query:'Galata Köprüsü Istanbul',photos:['b1','s2'],sources:['metro'],pick:'Best ship-watching pause'},
{id:'sapphire',cat:'tower',name:'Sapphire Skydeck & Vista',area:'4. Levent · European business district',view:'The skyscraper side of Istanbul: tall towers below you and the Bosphorus in the distance. Better for your high-rise-city mood than a mosque rooftop.',best:'Clear weekday afternoon, around 16:00–18:00; stay later only if your ticket / café permits.',time:['afternoon','sunset','night'],peace:2,calm:'Prefer a booked Vista window table over lingering in the busiest observation area. Neither space is private.',cost:'Paid observation / café. Current foreign-visitor price not verified.',budget:'ticket',access:'Vista advertises coffee and food, and no alcohol. Check observation hours, foreign ticket price and whether dining includes access; do not assume it does.',route:'Walk to Vezneciler → M2 to 4. Levent → follow signs to Sapphire. Confirm the observation entrance inside the complex.',mins:'55–75 min',coffee:true,coords:[41.0854,29.0051],query:'Istanbul Sapphire Observation Deck',photos:['v1','v2'],sources:['sapphire','vista','sapmap'],pick:'Best skyscraper alternative'},
{id:'camlica',cat:'tower',name:'Çamlıca Tower',area:'Küçük Çamlıca · Üsküdar',view:'A very high, wide city panorama across both sides of Istanbul. The observation deck is indoors behind glass; the restaurant offers a seated alternative.',best:'Friday 14:00–15:30 if visibility is good. Late afternoon also works; haze can flatten the panorama.',time:['afternoon','sunset'],peace:2,calm:'A viewing attraction rather than a silent room. For a long sit, ask about restaurant access and a window table separately.',cost:'Paid ticket; restaurant charges separate unless your booking says otherwise.',budget:'ticket',access:'Official observation floors 33/34; restaurant 39/40. Current foreign price and opening hours were not verified—confirm a 14:00 slot before paying.',route:'From hotel: T1 → Eminönü ferry to Üsküdar → M5 Kısıklı plus steep last-mile walk, or taxi. From Kuzguncuk on Friday, take a taxi.',mins:'75–105 min from hotel',coffee:true,coords:[41.0167,29.0656],query:'Çamlıca Kulesi Oyma Sokak 1 Istanbul',photos:['c1','c2'],sources:['camlica','metro'],pick:'Friday’s high-view option'},
{id:'galata',cat:'tower',name:'Galata Tower',area:'Bereketzade · Beyoğlu',view:'A close-up rooftop panorama over the Golden Horn and historic peninsula. More architectural intimacy than the modern skyscraper decks.',best:'Near opening at 08:30, or blue hour for photographs—not a long quiet sit.',time:['morning','sunset','night'],peace:1,calm:'A narrow, popular viewing balcony. There is no tower café to settle into; Mikla is a better seated alternative.',cost:'Published foreign adult admission: €30. Recheck before purchase.',budget:'ticket',access:'Official visitor page: 08:30–23:00, last entry 22:00. Museum access, not a restaurant booking.',route:'T1 to Karaköy → 10–15 min uphill walk. The tower is on Büyük Hendek Caddesi, Bereketzade.',mins:'30–45 min',coffee:false,coords:[41.0256,28.9741],query:'Galata Kulesi Istanbul',photos:['g1','k1'],sources:['galata','galatam'],pick:'Photo stop, not a lounge'},
{id:'crossing',cat:'boat',name:'Eminönü ↔ Üsküdar ferry',area:'Public ferry · two continents',view:'The skyline moves past while you sit: domes, towers, wakes and working ships. The most practical way to put a water view into your day.',best:'Friday outbound target 09:00. Return after your Salacak sunset, using the next posted sailing around 20:00–20:30.',time:['morning','sunset','night'],peace:2,calm:'An outside seat away from doors is the aim, not a guaranteed quiet deck. Wind and commuter crowds vary.',cost:'Ordinary ferry fare; check current tariff / Istanbulkart rules.',budget:'budget',access:'09:00 is a published Eminönü departure, not an arrival. Check the day’s timetable and pier. Not the same ticket as a sightseeing tour.',route:'T1 to Eminönü → follow Şehir Hatları signs for Üsküdar. Arrive about 15 min early and confirm the destination before boarding.',mins:'20–30 min to pier + sailing',coffee:false,coords:[41.019,28.9765],query:'Eminönü Üsküdar Şehir Hatları İskelesi Istanbul',photos:['b1','a1'],sources:['ferry'],pick:'Best everyday water view'},
{id:'short',cat:'boat',name:'Short Bosphorus Tour',area:'Şehir Hatları · Eminönü departure',view:'A longer seated spell on the water without losing an entire sightseeing day. This is the cruise chosen for Thursday.',best:'Thursday 14:40 departure; be at the official pier around 14:05. Allow roughly two hours and verify return time.',time:['afternoon'],peace:2,calm:'Choose an outdoor seat away from speakers when boarding. Sightseeing passengers will move around for photos; not a private cruise.',cost:'Published foreign adult fare: ₺340. Recheck official tariff.',budget:'budget',access:'Current daily departure: Eminönü 14:40; Üsküdar 14:55; Ortaköy 15:10. The extra 16:45 Eminönü sailing is listed for official holidays only.',route:'T1 to Eminönü → official Şehir Hatları Bosphorus-tour ticket office / pier. Do not board the first boat offered by a street seller.',mins:'20–30 min to pier',coffee:false,coords:[41.0185,28.9758],query:'Şehir Hatları Boğaz Turu Eminönü Istanbul',photos:['b1','t1'],sources:['short','fares'],pick:'Thursday’s cruise'},
{id:'long',cat:'boat',name:'Long Bosphorus Tour',area:'Eminönü → Anadolu Kavağı → return',view:'The broadest water journey in this catalogue: the city thins into greener shores towards the northern Bosphorus.',best:'Published daily departure 10:35 from Eminönü; Anadolu Kavağı arrival 12:25, return departure 15:00.',time:['morning','afternoon'],peace:2,calm:'A long seated journey, but still a public sightseeing boat. Avoid making restaurant bookings immediately after the return.',cost:'Published foreign adult return fare: ₺640. Recheck tariff.',budget:'budget',access:'Treat this as a roughly six-hour alternative, not an extra on Thursday. Current return timing and service operation must be checked.',route:'T1 to Eminönü → official Bosphorus-tour pier. Arrive 30 min early. Keep your return ticket and verify the return sailing at Anadolu Kavağı.',mins:'20–30 min to pier + half-day tour',coffee:false,coords:[41.1747,29.0893],query:'Şehir Hatları Boğaz Turu Eminönü Istanbul',photos:['b1','o2'],sources:['long','fares'],pick:'Swap, never add'}
];
const HOTEL='Vizyon Hotel Center, Gedikpaşa Camii Sokağı 54/A, Istanbul';
const FOOD=[
['Grilled köfte','Tarihi Sultanahmet Köftecisi Selim Usta','Sultanahmet · arrival night or Thursday','A simple first dinner: grilled beef meatballs. Ask for the current sides and bill; several similarly named restaurants exist.','Tarihi Sultanahmet Köftecisi Selim Usta Istanbul','kofte'],
['Kuru fasulye','Erzincanlı Ali Baba','Opposite Süleymaniye · Thursday lunch','Slow-cooked beans, with rice and pickles as optional sides. A natural stop after the mosque viewpoint. Confirm whether the day’s beans contain meat.','Erzincanlı Ali Baba Süleymaniye Istanbul','beans'],
['Pistachio baklava','Karaköy Güllüoğlu','Kemankeş Caddesi 67 · Thursday after cruise','Try a small portion rather than a large mixed box. Contains nuts; many varieties contain dairy. This is a food stop, not a quiet panoramic café.','Karaköy Güllüoğlu Kemankeş Caddesi 67','baklava'],
['Charcoal döner / dürüm','Metet Közde Döner','İcadiye Caddesi 10, Kuzguncuk · Friday lunch','A good route-compatible lunch after Fethipaşa. Use the current address, not older listings on Tufan Sokak.','Metet Közde Döner İcadiye Caddesi 10 Kuzguncuk','doner'],
['Kumpir','Ortaköy square stalls','Only when visiting Ortaköy','A large baked potato with fillings. Pick the toppings you actually like; ask about meat and sauces. Choose a busy, clean stall rather than treating every vendor as equivalent.','Ortaköy Kumpirciler Istanbul','ortakoy'],
['Wood-fired seafood','Mürver','Karaköy · optional arrival-night splurge','Choose from the current seasonal menu. Reserve for the view, but ask about music and terrace seating before committing.','Mürver Restaurant Istanbul','murver']
];
const DAYS=[
{key:'9',label:'Wed 9 Sep',title:'Arrive. Unpack. Watch the city settle.',intro:'Afternoon arrival at IST. Keep this evening flexible: no non-refundable dinner attached to an uncertain airport arrival.',sun:'Sunrise 06:38 · sunset 19:23 · dusk 19:51',color:'#bc6947',stops:[
['Afternoon','IST → hotel','Finish arrival formalities and take your chosen transfer to Vizyon Hotel Center. Allow generous traffic and check-in time.',HOTEL,[41.006,28.968],'driving'],
['After check-in','Rest first','Keep 45–60 minutes for a shower, water and a proper pause. You have two full days ahead.',HOTEL,[41.006,28.968],'walking'],
['18:15 · optional','Mürver early dinner','Only add this when checked in by about 17:00 and a suitable table is available. Otherwise stay local; do not rush across the city.', 'Mürver Restaurant Istanbul',[41.0238,28.979],'transit','murver'],
['Easy evening','Sultanahmet lights + köfte','Use the public squares for illuminated exteriors. Selim Usta is a convenient food option; opening and seating must be checked on the day.','Tarihi Sultanahmet Köftecisi Selim Usta Istanbul',[41.008,28.9765],'transit']
]},
{key:'10',label:'Thu 10 Sep',title:'Old-city heights. A boat. One exceptional rooftop.',intro:'The main European-side day. Keep the morning gentle and the afternoon cruise fixed; Mikla is the evening booking to prioritise.',sun:'Sunrise 06:39 · sunset 19:22 · dusk 19:49',color:'#24786d',stops:[
['06:15–07:15 · optional','Sultanahmet at first light','A nearby dawn walk, not a compulsory early start. Photograph the exteriors, then return for breakfast or more sleep.','Sultanahmet Meydanı Istanbul',[41.0065,28.9756],'walking'],
['09:30–10:30','Süleymaniye terrace','Walk from the hotel. Enjoy the panorama and the quieter atmosphere, respecting mosque access and prayer.','Süleymaniye Camii Istanbul',[41.0163,28.9639],'walking','sule'],
['11:15–12:00','Beans at Ali Baba','Lunch near the viewpoint. Afterwards, take your time descending towards Eminönü; the next hour is deliberately unstructured.','Erzincanlı Ali Baba Süleymaniye Istanbul',[41.0158,28.9645],'walking'],
['12:15–13:45','Waterfront pause','Watch working boats around Eminönü, buy water and take a seated break. Do not turn the free time into another hill to climb.','Eminönü Meydanı Istanbul',[41.0175,28.9707],'walking'],
['14:05 at pier · 14:40 sailing','Short Bosphorus Tour','Buy / confirm the official ₺340 foreign-adult ticket. Allow about two hours; verify the return time and sailing at the pier.','Şehir Hatları Boğaz Turu Eminönü Istanbul',[41.0185,28.9758],'walking','short'],
['About 17:00','Bridge walk + baklava','After returning, cross towards Karaköy and stop at Güllüoğlu. The actual ferry return controls this timing.','Karaköy Güllüoğlu Kemankeş Caddesi 67',[41.0236,28.9791],'walking'],
['18:00–20:15','Mikla: sunset into city lights','Use Tünel / a taxi for the hill when tired. Request a seated outdoor view table. Sunset is 19:22; no reservation has been made.','Mikla Restaurant The Marmara Pera Istanbul',[41.031,28.9751],'walking','mikla'],
['After dinner','Return to Vizyon','M2 from Şişhane to Vezneciler plus the final walk, or a taxi. Save energy for the Asian side tomorrow.',HOTEL,[41.006,28.968],'transit']
]},
{key:'11',label:'Fri 11 Sep',title:'A leafy sit. A high view. Sunset across the water.',intro:'The calmer Asian-side day. Choose Çamlıca Tower OR Nakkaştepe in the afternoon—not both. End at Salacak, with time left for the walk back to the ferry.',sun:'Sunrise 06:40 · sunset 19:20 · dusk 19:48',color:'#776494',stops:[
['08:30 at pier · target 09:00','Eminönü → Üsküdar','Use the published 09:00 departure only after checking that day’s service. Take the next available crossing if needed.','Eminönü Üsküdar Şehir Hatları İskelesi Istanbul',[41.019,28.9765],'transit','crossing'],
['On arrival','Üsküdar pier','Start the waterfront walk north towards Fethipaşa; a taxi is a reasonable way to avoid the steep final climb.','Üsküdar Şehir Hatları İskelesi Istanbul',[41.0265,29.015],'transit'],
['10:00–11:30','Fethipaşa: your thinking time','Choose an upper-path bench or a café table away from the busiest edge. Keep the phone in your pocket for part of this stop.','Fethipaşa Korusu Üsküdar Istanbul',[41.029,29.023],'walking','fethi'],
['12:00–13:00','Kuzguncuk + Metet lunch','Stroll the neighbourhood, then try charcoal döner at the current İcadiye Caddesi address.','Metet Közde Döner İcadiye Caddesi 10 Kuzguncuk',[41.034,29.03],'walking'],
['14:00–15:30 · book a slot','Çamlıca Tower OR Nakkaştepe','Take a taxi to a confirmed tower slot on a clear day. Prefer the park instead when you want fresh air or lower cost. The map shows the tower version.','Çamlıca Kulesi Istanbul',[41.0167,29.0656],'driving','camlica'],
['15:30–17:30','Leave a real gap','Use the buffer for a drink, rest and an unhurried transfer back to the waterfront. There is no bonus attraction to squeeze in.','Salacak Sahili Üsküdar Istanbul',[41.018,29.0118],'driving'],
['17:45–19:40','Salacak sunset','Find a seat away from the most obvious photo spot. Sunset at 19:20; linger for the first lights, then begin the return walk.','Salacak Sahili Üsküdar Istanbul',[41.018,29.0118],'walking','salacak'],
['Around 20:00–20:30','Next posted ferry home','Allow 20–25 minutes back to Üsküdar pier before boarding. Check the live timetable; a ferry at 19:40 would be too tight. Then T1 back to the hotel.','Üsküdar Şehir Hatları İskelesi Istanbul',[41.0265,29.015],'walking'],
['About 21:00–21:30','Pack and sleep','Confirm tomorrow’s pickup, terminal and flight time. The return time is an estimate, not a transport guarantee.',HOTEL,[41.006,28.968],'transit']
]},
{key:'12',label:'Sat 12 Sep',title:'Airport morning. No last-minute sightseeing.',intro:'Based on your roughly 10:00 flight home to Dublin, with IST assumed as the departure airport. Check the ticket: a different airport or time changes this plan.',sun:'Sunrise 06:41 · flight about 10:00',color:'#55616d',stops:[
['05:45–06:00 · suggested','Pre-arranged hotel pickup','Ask the hotel to arrange / confirm a transfer. This is a conservative planning window, not a booked car or a live traffic prediction.',HOTEL,[41.006,28.968],'driving'],
['Around 07:00','Aim to be inside IST','Turkish Airlines recommends arriving three hours before an international flight. Allow more time when your airline or conditions require it.','Istanbul Airport IST Departures',[41.2753,28.752],'driving'],
['Around 10:00','Flight to Dublin','No Saturday evening cruise fits your dates. Verify your exact flight details rather than relying on the approximate time in this guide.','Istanbul Airport IST',[41.2753,28.752],'walking']
]}
];